flaskmodel/users/models.py
class User():
    pass


class Permissions():
    pass

flaskmodel/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=4, max=20),])
    email = StringField('Email', validators=[DataRequired(), Email(),])
    password = PasswordField('Senha', validators=[DataRequired(), ])
    check_password = PasswordField('Verificação de Senha', validators=[DataRequired(), EqualTo('password')])
    submit_button = SubmitField('Cadastrar')

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email(),])
    password = PasswordField('Senha', validators=[DataRequired(), ])
    submit_button = SubmitField('Entrar')

flaskmodel/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy

from .main.routes import main
from .errors.routes import errors
from .users.routes import users

def create_app():
    app = Flask(__name__)

    app.config['SECRET_KEY'] = 'senha_muito_segura'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///banco_de_dados.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True

    bootstrap = Bootstrap(app) 

    db = SQLAlchemy(app)

    app.register_blueprint(main)
    app.register_blueprint(errors)
    app.register_blueprint(users)

    return app

flaskmodel/data/__init__.py
from flask import Blueprint

data = Blueprint('data',__name__)

flaskmodel/data/routes.py
from . import data
from flask import render_template

flaskmodel/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

flaskmodel/main/routes.py
from flask import render_template
from . import main

@main.route('/')
@main.route('/home')
def index():
    return render_template('main/index.html')

flaskmodel/users/__init__.py
from flask import Blueprint

users = Blueprint('users',__name__)

flaskmodel/users/routes.py
from . import users
from .forms import RegistrationForm, LoginForm
from flask import render_template, redirect, url_for, flash


@users.route('/register', methods=['GET','POST'])
@users.route('/cadastro', methods=['GET','POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        return redirect(url_for('main.index'))
    else:
        return render_template('users/cadastro.html', form= form)


@users.route('/login', methods=['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        return redirect(url_for('main.index'))
    else:
        return render_template('users/login.html', form=form)

flaskmodel/templates/base.html
{% extends "bootstrap/base.html" %}


{% block html_attribs %} lang="pt-BR" {% endblock html_attribs %} 


{% block title %} Flask Model {% endblock title %}


{% block metas %} 
    {{super()}}

    <!-- Minhas configurações -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
{% endblock metas %} 


{% block navbar %}
    <div class="navbar navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle"
            data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('main.index') }}">Flask Model</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{{ url_for('users.register') }}">Cadastro</a></li>
          </ul>
          <ul class="nav navbar-nav">
            <li><a href="{{ url_for('users.login') }}">Login</a></li>
          </ul>
        </div>
      </div>
    </div>
{% endblock %}}


{% block content %}
{% endblock %}

flaskmodel/templates/main/index.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <div class="content-section"><h1>Bem vindo!</h1></div>
</div>
{% endblock %}

flaskmodel/templates/users/cadastro.html
{% extends 'base.html' %} {% block content %}
<div class="container">
    
<div class="content-section">
            <form method="POST" action="">
                <!--form.hidden_tag() é uma proteção contra ataques-->
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Cadastro</legend>
                    
                        <div class="form-group">
                            {{ form.username.label(class="form-control-label") }} 
                            {{ form.username(class="form-control form-control-lg") }}
                        </div>

                        <div class="form-group">
                            {{ form.email.label(class="form-control-label") }} 
                            {{ form.email(class="form-control form-control-lg") }}
                        </div>

                        <div class="form-group">
                            {{ form.password.label(class="form-control-label") }} 
                            {{ form.password(class="form-control form-control-lg") }}
                        </div>

                        <div class="form-group">
                            {{ form.check_password.label(class="form-control-label") }} 
                            {{ form.check_password(class="form-control form-control-lg") }}
                        </div>

                <div class="form-group">
                    {{ form.submit_button(class="btn btn-outline-info") }}
                </div>
            </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Já possui cadastro?
                <a class="ml-2" href="{{ url_for('users.login') }}">Faça o login!</a>
            </small>
        </div>
    </div>
</div>
  {% endblock %}

flaskmodel/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="content-section">
        <form method="POST" action="">
            <!--form.hidden_tag() é uma proteção contra ataques-->
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Cadastro</legend>
                <div class="form-group">
                     {{ form.email.label(class="form-control-label") }}
                     {{ form.email(class="form-control form-control-lg") }}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {{ form.password(class="form-control form-control-lg") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit_button(class="btn btn-outline-info") }}
            </div>  
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Ainda não possui cadastro? <a class="ml-2" href="{{ url_for('users.register') }}">Cadastre-se aqui!</a>
            </small>
        </div>
    </div>
</div>
{% endblock %}